Theme: Jekyll-theme-architect
Title: Welcome to Instabug Doniations website
Description: Our target amount is to collect 25K EGP in donations.
This basically means sending shonat ramadan to more than 300 families
all around Egypt and helping 2 families in creating a sustainable income through a small project.
